title: github xd
author: Jeff Chen
email: jchen13@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  school lol

# social links
github_username:  jchen1027 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
